Ed = 2;
Ep = 2;
U = 1;
dim = 200;
zone = 1;
[kx, ky] = meshgrid(linspace(-pi*zone,pi*zone,dim), linspace(-pi*zone,pi*zone,dim));
E = sqrt((Ed-Ep)^2 + 16*U^2*(sin(kx/2).^2+sin(ky/2).^2));
Eplus = (Ed+Ep)/2 + E/2;
Eminus = (Ed+Ep)/2 - E/2;
Esaddle = (Ed+Ep)/2 + sqrt((Ed-Ep)^2 + 16*U^2)/2;
Eprime = sort(reshape(Eplus, 1, dim^2));
Ef1 = Eprime(round(dim^2*0.5));
Ef2 = Eprime(round(dim^2*0.35));
deltaE = Esaddle - Ef1;

figure;
axis('square');
hold on;
mesh(kx, ky, Eplus);

% figure;
% subplot(1,3,1);
% axis('square');
% hold on;
% mesh(kx, ky, Eplus);
% subplot(1,3,2);
% axis('square');
% hold on;
% mesh(kx, ky, ones(dim,dim)*Ef1);
% mesh(kx, ky, Eplus);
% subplot(1,3,3);
% axis('square');
% hold on;
% mesh(kx, ky, ones(dim,dim)*Ef2);
% mesh(kx, ky, Eplus);