P = [0.2 : 0.01 : 2];
H = 80 * P.^(-0.25);
figure;
hold on;
xlim([min(H),max(H)]);
ylim([0,1.5]);
set(gca, 'fontsize', 30);
xlabel('H');
ylabel('P');
plot(H, P, 'color', 'b', 'linewidth', 2);
plot(80*[1,1], [0,max(P)], 'color', 'k', 'linewidth', 2, 'linestyle', ':');
plot(100*[1,1], [0,max(P)], 'color', 'k', 'linewidth', 2, 'linestyle', ':');
plot([min(H),max(H)], [1,1], 'color', 'k', 'linewidth', 2, 'linestyle', ':');
plot([min(H),max(H)], (8/10)^4*[1,1], 'color', 'k', 'linewidth', 2, 'linestyle', ':');

P = [0.2 : 0.01 : 2];
H = 150 * P.^(-0.25);
figure;
hold on;
xlim([min(H),max(H)]);
ylim([0,1.5]);
set(gca, 'fontsize', 30);
xlabel('H');
ylabel('P');
plot(H, P, 'color', 'b', 'linewidth', 2);
plot(150*[1,1], [0,max(P)], 'color', 'k', 'linewidth', 2, 'linestyle', ':');
plot([min(H),max(H)], [1,1], 'color', 'k', 'linewidth', 2, 'linestyle', ':');

P = [0.2 : 0.01 : 2];
H = 80 * P.^(-0.25);
figure;
hold on;
xlim([min(H),max(H)]);
ylim([0,1.5]);
set(gca, 'fontsize', 30);
xlabel('H');
ylabel('P');
plot(H, P, 'color', 'b', 'linewidth', 2);
plot(80*[1,1], [0,max(P)], 'color', 'k', 'linewidth', 2, 'linestyle', ':');
plot(100*[1,1], [0,max(P)], 'color', 'k', 'linewidth', 2, 'linestyle', ':');
plot(80*0.75^(-0.25)*[1,1], [0,max(P)], 'color', 'k', 'linewidth', 2, 'linestyle', ':');
plot([min(H),max(H)], [1,1], 'color', 'k', 'linewidth', 2, 'linestyle', ':');
plot([min(H),max(H)], (8/10)^4*[1,1], 'color', 'k', 'linewidth', 2, 'linestyle', ':');
plot([min(H),max(H)], 0.75*[1,1], 'color', 'k', 'linewidth', 2, 'linestyle', ':');