L= [0, 10];
MRPL = -4.5*L + 45;
w = L + 8;
MCL = 2*L + 8;

figure;
hold on;
set(gca, 'fontsize', 20);
xlim([4, 8]);
ylim([10, 30]);
xlabel('L');
ylabel('w');
plot(L, MRPL, 'color', 'b', 'linewidth', 2);
plot(L, w, 'color', 'r', 'linewidth', 2);
legend('MRPL', 'S_L');
plot([74/11,74/11], [0,50], 'color', 'k', 'linewidth', 2, 'linestyle', '--');

figure;
hold on;
set(gca, 'fontsize', 20);
xlim([4, 8]);
ylim([10, 30]);
xlabel('L');
ylabel('w');
plot(L, MRPL, 'color', 'b', 'linewidth', 2);
plot(L, MCL, 'color', 'm', 'linewidth', 2);
plot(L, w, 'color', 'r', 'linewidth', 2);
legend('MRPL', 'MCL', 'S_L');
plot([74/13,74/13], [0,50], 'color', 'k', 'linewidth', 2, 'linestyle', '--');

figure;
hold on;
set(gca, 'fontsize', 20);
xlim([4, 8]);
ylim([10, 30]);
xlabel('L');
ylabel('w');
plot(L, MRPL, 'color', 'b', 'linewidth', 2);
plot(L, MCL, 'color', 'm', 'linewidth', 2);
plot(L, w, 'color', 'r', 'linewidth', 2);
plot(L, [16,16], 'color', 'g', 'linewidth', 2);
legend('MRPL', 'MCL', 'S_L', '$16');
plot([74/13,74/13], [0,50], 'color', 'k', 'linewidth', 2, 'linestyle', '--');
plot([74/11,74/11], [0,50], 'color', 'k', 'linewidth', 2, 'linestyle', '--');
plot([58/9,58/9], [0,50], 'color', 'k', 'linewidth', 2, 'linestyle', '--');

figure;
hold on;
set(gca, 'fontsize', 20);
xlim([4, 8]);
ylim([10, 30]);
xlabel('L');
ylabel('w');
plot(L, MRPL, 'color', 'b', 'linewidth', 2);
plot(L, MCL, 'color', 'm', 'linewidth', 2);
plot(L, w, 'color', 'r', 'linewidth', 2);
plot(L, [20,20], 'color', 'g', 'linewidth', 2);
legend('MRPL', 'MCL', 'S_L', '$20');
plot([74/13,74/13], [0,50], 'color', 'k', 'linewidth', 2, 'linestyle', '--');
plot([74/11,74/11], [0,50], 'color', 'k', 'linewidth', 2, 'linestyle', '--');
plot([50/9,50/9], [0,50], 'color', 'k', 'linewidth', 2, 'linestyle', '--');
